### PR TITLE
Add Dark Mode documentation

### PR DESCRIPTION
**Pull request by pspeter3**
Add it to the README so people do not need to find https://github.com/tailwindlabs/tailwindcss-typography/issues/69

### CODE REVIEW

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

We have "official" dark mode support in the pipeline (mainly about our preferred defaults).
Will keep this PR open and will probably update it once we have decided what the defaults should be.

Just wanted to let you know already!

**Comment by pspeter3** [comment]
No worries and thanks for letting me know! I figured I would just add the PR if it was helpful for y'all. Trying to do what I wish people would do for my OSS projects. Thanks for everything you're doing here and on Headless UI.

**Comment by reinink** [comment]
@pspeter3 Hey thanks for this! As @RobinMalfait noted, we've now added first-class support for dark mode to the typography plugin via the new `dark:prose-invert` class, and have updated the documentation on the website to include instructions on how to use this:

https://tailwindcss.com/docs/typography-plugin#adapting-to-dark-mode

Definitely appreciate you trying to help out 💪

**Comment by pspeter3** [comment]
No problem, happy to help! Thanks for the real dark mode!

**Pull request closed without merging**
