### PR TITLE
Remove typography styles from `not-prose` elements in addition to their children

### LINKED ISSUE #299: not-prose doesn't ignore the element itself
### What version of @tailwindcss/typography are you using?

v0.5.9

### What version of Node.js are you using?

browser

### What browser are you using?

Occurs on all

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/Y1RYnKWHcJ

### Describe your issue

When an element has the `not-prose` class, only child elements gets ignored. But it would be useful to have also the element itself ignored. For example for link components who get inserted inside a prose element

## Example:
https://play.tailwindcss.com/Y1RYnKWHcJ

The generated CSS by the CDN is:
```css
.prose :where(a):not(:where([class~="not-prose"] *)) {
  color: var(--tw-prose-links);
  text-decoration: underline;
  font-weight: 500;
}
```

but should be

```css
.prose :where(a):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
  color: var(--tw-prose-links);
  text-decoration: underline;
  font-weight: 500;
}
```

Like that, the element itself would also be ignored.

### PR DESCRIPTION
**Pull request by jonnitto**
Close #299

### CODE REVIEW

**Comment by adamwathan** [comment]
For others on the team when thinking through this — we’ll want to think through the impact of this as a breaking change, since adding this class to an element like `blockquote` would remove margins now.

**Comment by jonnitto** [comment]
Perhaps we could make this configurable?

**Comment by jonnitto** [comment]
I have a working prototype for that.

The plugin options would look something like that…

```js
module.exports = plugin.withOptions(
  ({ className = 'prose', target = 'modern', includeNotProsedElement = false } = {}) => {
    return function ({ addVariant, addComponents, theme, prefix }) {
      let modifiers = theme('typography')

     
      let options = { className, prefix, includeNotProsedElement }

…
```

But how you would name such a setting? Naming is hard 😉

**Comment by reinink** [comment]
Hey thanks for this contribution @jonnitto!

**Comment by robdekort** [comment]
Hey folks. This turned out a breaking change for my sites and a widely used Starter Kit I run for Statamic as I used the `not-prose` class to add vertical margins to elements within the `prose` class. 

Maybe I could use that config option, but tbh I'm not really sure how to implement that. Is there someone willing to explain this a bit?

Thanks a bunch in advance! 🙌

**Comment by robdekort** [comment]
Never mind, figured out a different way of doing this going forward.

**Comment by Strajk** [comment]
Heya, this change turned out to be pretty breaking for [Protocol](https://tailwindui.com/templates/protocol) template

Repro: Download protocol, install deps, should be broken with 5.10

Screen 2023-10-02 at 08 19 32

**Comment by b5** [comment]
Is there recommended fix for `not-prose` in the protocol template moving forward? I'm totally fine with the breaking change, but it'd be great to have a recommended approach, even just a set of tailwind classes to drop into an inner-div from a `not-prose` parent would work

**Comment by thecrypticace** [comment]
@Strajk @b5 hey yeah there is. We spent a little bit of time figuring out a simple update to the template to work around these changes in the typography plugin. We've updated our live preview as well as the download link for the template to address these issues caused by the change.

A summary of what we've done is:

1. In `typography.ts`, we removed the `> *` block of styles from the config
2. In `src/components/Prose.ts`, we added classes that apply these same styles to the `<Prose>` component using the variant `[html_:where(&>*)]`. This gives them the right specifify to work the same way they did before while generally fixing the problem with `not-prose`.
3. In `src/components/Code.tsx`, we removed `not-prose` from `containerClassName`
4. In `src/components/Code.tsx`, we wrapped the headers and panels in a `<div className="not-prose">`

The diffs look like this:

1. In `typography.ts`:

```diff
- // Layout
- '> *': {
-   maxWidth: theme('maxWidth.2xl'),
-   marginLeft: 'auto',
-   marginRight: 'auto',
-   '@screen lg': {
-     maxWidth: theme('maxWidth.3xl'),
-     marginLeft: `calc(50% - min(50%, ${theme('maxWidth.lg')}))`,
-     marginRight: `calc(50% - min(50%, ${theme('maxWidth.lg')}))`,
-   },
- },
```

2. In `src/components/Prose.ts`:

```diff
    <Component
-      className={clsx(className, 'prose dark:prose-invert')}
+      className={clsx(
+        className,
+        'prose dark:prose-invert',
+        // `html :where(& > *)` is used to select all direct children without an increase in specificity like you'd get from just `& > *`
+        '[html_:where(&>*)]:mx-auto [html_:where(&>*)]:max-w-2xl [html_:where(&>*)]:lg:mx-[calc(50%-min(50%,theme(maxWidth.lg)))] [html_:where(&>*)]:lg:max-w-3xl',
+      )}
      {...props}
    />
```

3. In `src/components/Code.tsx`

```diff
   let containerClassName =
-    'not-prose my-6 overflow-hidden rounded-2xl bg-zinc-900 shadow-md dark:ring-1 dark:ring-white/10'
+    'my-6 overflow-hidden rounded-2xl bg-zinc-900 shadow-md dark:ring-1 dark:ring-white/10'
```

4. In `src/components/Code.tsx`

```diff
  <Tab.Group {...tabGroupProps} className={containerClassName}>
-    {header}
-    {panels}
+    <div className="not-prose">
+      {header}
+      {panels}
+    </div>
  </Tab.Group>
```

```diff
  <div className={containerClassName}>
-    {header}
-    {panels}
+    <div className="not-prose">
+      {header}
+      {panels}
+    </div>
  </div>
```

Hope that helps and let us know if you notice anything else! ✨

**Comment by rubendinho** [comment]
This was a breaking change for our docs site as well. It really doesn't make sense to add this type of behavior change into a patch update, given that the project follows Semantic Versioning.

**Pull request merged**
